# version: '3.8'
# services:
#   jenkins:
#     build:
#       context: .
#       dockerfile: Dockerfile.window
#     container_name: jenkins
#     # image: jenkins/jenkins:2.469
#     # user: root
#     # privileged: true
#     environment:
#       - TZ=Asia/Seoul
#       - DOCKER_HOST=tcp://docker:2376
#       - DOCKER_CERT_PATH=/certs/client
#       - DOCKER_TLS_VERIFY=1
#     ports:
#       - 8080:8080
#       - 50000:50000
#     volumes:
#       - ./jenkins/config:/var/jenkins_home
#       # - //var/run/docker.sock:/var/run/docker.sock
#       - jenkins-docker-certs:/certs/client:ro

# volumes:
#   jenkins-docker-certs:

version: '3'

services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.window
    container_name: jenkins
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - ./jenkins/config:/var/jenkins_home
      - docker_certs:/certs/client:ro
    environment:
      DOCKER_HOST: "tcp://docker:2376"
      DOCKER_TLS_VERIFY: "1"
      DOCKER_CERT_PATH: "/certs/client"
    depends_on:
      - docker

  docker:
    image: docker:25-dind
    container_name: docker
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: "/certs"
    volumes:
      - ./jenkins/config:/var/jenkins_home
      - docker_certs:/certs/client

volumes:
  docker_certs:
